mod ui_language;
mod ui_left_panel_1_pack;
mod ui_left_panel_1_unpack;
mod ui_play_sound;
pub mod ui_main;
pub mod ui_defaults;
mod ui_left_panel_2_konwersja;
mod ui_right_panel_info_0;
mod ui_right_panel_info_1;
mod ui_right_panel_info_2;
mod ui_right_panel_info_3;
mod ui_right_panel_settings;
mod ui_right_panel_info_4;
mod ui_right_panel_debug_0;
mod ui_change_font;
mod ui_left_panel_2_foto_laczenie;